extraVolumes:
  - name: pods
    hostPath:
        path: /var/lib/kubelet/pods
extraVolumeMounts:
  - name: pods
    mountPath: /var/lib/kubelet/pods
    readOnly: true

daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: log
        paths:
          - /var/lib/kubelet/pods/*/volumes/**/*.log
      processors:
      - add_kubernetes_metadata:
        host: ${NODE_NAME}
        default_indexers.enabled: false
        default_matchers.enabled: false
        indexers:
          - pod_uid:
        matchers:
        - logs_path:
            logs_path: "/var/lib/kubelet/pods"
            resource_type: 'pod'
      - script:
        lang: javascript
        id: format_k8s
        tag: enable
        source: >
          function process(event) {
              var k8s=event.Get("kubernetes");
              event.Put("app_name", k8s.labels['app_kubernetes_io/name']);
              event.Put("app_namespace", k8s.namespace);
              event.Put("pod_name", k8s.pod.name);
              event.Put("pod_ip", k8s.pod.ip);
              event.Put("node_name", k8s.node.name);
          }
      - drop_fields:
        fields: ["host", "ecs", "log", "agent", "input", "kubernetes"]
        ignore_missing: true

      setup.ilm.enabled: false
      setup.template.name: "app-metrics"
      setup.template.pattern: "app-metrics-*"
    
      # filebeat.inputs:
      # - type: container
      #   paths:
      #     - /var/log/containers/*.log
      #   processors:
      #   - add_kubernetes_metadata:
      #       host: ${NODE_NAME}
      #       matchers:
      #       - logs_path:
      #           logs_path: "/var/log/containers/"

      output.elasticsearch:
        hosts: 'elasticsearch-master.share:9200'
        index: "app-metrics-%{[agent.version]}-%{+yyyy.MM.dd}"

# /var/log/containers/ 命名格式：[podName]_[nameSpace]_[depoymentName]-[containerId].log
