extraVolumes:
  - name: pods
    hostPath:
        path: /var/lib/kubelet/pods
extraVolumeMounts:
  - name: pods
    mountPath: /var/lib/kubelet/pods
    readOnly: true

daemonset:
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: log
        paths:
          - /var/lib/kubelet/pods/*/volumes/**/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            default_indexers.enabled: false
            default_matchers.enabled: false
            indexers:
              - pod_uid:
            matchers:
            - logs_path:
                logs_path: "/var/lib/kubelet/pods"
                resource_type: 'pod'

      setup.ilm.enabled: false
      setup.template.name: "app-metrics"
      setup.template.pattern: "app-metrics-*"
    
      # filebeat.inputs:
      # - type: container
      #   paths:
      #     - /var/log/containers/*.log
      #   processors:
      #   - add_kubernetes_metadata:
      #       host: ${NODE_NAME}
      #       matchers:
      #       - logs_path:
      #           logs_path: "/var/log/containers/"

      output.elasticsearch:
        hosts: 'elasticsearch-master.share:9200'
        index: "app-metrics-%{[agent.version]}-%{+yyyy.MM.dd}"

# /var/log/containers/ 命名格式：[podName]_[nameSpace]_[depoymentName]-[containerId].log
