esConfig: 
 elasticsearch.yml: |
    xpack.security.enabled: true

extraEnvs:
  - name: ELASTIC_USERNAME
    value: admin
  - name: ELASTIC_PASSWORD
    value: admin@es

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  storageClassName: "nfs-client"
  resources:
    requests:
      storage: 20Gi