controller:
  image:
    repository: bitnami/nginx-ingress-controller
    tag: "0.46.0"
    digest: null
  hostNetwork: true
  kind: DaemonSet

defaultBackend:
  enabled: false

tcp: 
  6379: "share/redis-headless:6379"
  3306: "share/mysql:3306"
